# Generated by Django 4.2 on 2023-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
