# Generated by Django 4.2 on 2023-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_currency_create_at_alter_currency_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
