# Generated by Django 4.2 on 2023-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_news_remove_apply_email_remove_apply_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='topic',
            field=models.CharField(max_length=80),
        ),
    ]
