# Generated by Django 4.2 on 2023-05-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_newstranslation_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
